name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make run CC=gcc CXX=g++ ARGS=test.ini

  windows-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make run OS=Windows_NT CC=clang CXX=clang++ ARGS=test.ini

  osx-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make run CC=clang CXX=clang++ ARGS=test.ini
